sudo: required
language: php
php:
  - '7.1'
before_install:
  - sudo apt update
  - sudo apt install -y iptables-persistent
before_script:
  - cd src
  - composer install --dev
  - cp env.travis .env
  - touch storage/app/db.sqlite
  - php artisan key:generate
  - php artisan migrate
  - php artisan config:reset
script: vendor/bin/phpunit && vendor/bin/phpcs
notifications:
    slack: cylab-be:jIZ8x1I8D5tD7cOHcelYm5L7
