sudo: required
language: php
php:
  - '7.1'
before_script:
  - cd laravel-test
  - composer install --dev
  - cp env.travis .env
  - echo "travis ALL=NOPASSWD: /home/travis/build/RUCD/data-diode/laravel-test/app/Scripts/datadiode.sh" | sudo EDITOR='tee -a' visudo
  - touch storage/app/db.sqlite
  - touch database/database.sqlite
  - php artisan key:generate
  - php artisan migrate
script: vendor/bin/phpunit && vendor/bin/phpcs
notifications:
    slack: cylab-be:jIZ8x1I8D5tD7cOHcelYm5L7
